runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: 'revisioner-interview:us-central1:revisioner-interview-db'
env_variables:
  SQL_USER: 'apppp'
  SQL_PASSWORD: 'ggg-revisioner'
  SQL_DATABASE: 'revisioner'
  INSTANCE_CONNECTION_NAME: 'revisioner-interview:us-central1:revisioner-interview-db'
